[package]
name = "dca-rs"
version = "0.1.0"
authors = ["Nicholas Stafie <nicholasstafie@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[dependencies]
clap = "*"
opus = "*"
serde = "*"
serde_json = "*"
byteorder = "*"
